vi-apps:
  hosts:
    ansible_master:
      ansible_host: 127.0.0.1
      ansible_user: admin
    vi-app-1:
      ansible_host: 172.31.22.43
      ansible_user: admin
    vi-app-2:
      ansible_host: 172.31.22.149
      ansible_user: admin